### 기대 수명 회귀 예측

#### Features

- Country: 국가
- Year: 연도
- Status: 개발도상국(Developing) / 선진국(Developed)
- Adult Mortality: 성인 사망률 (1000명 기준 15-60세 인구의 사망 확률)
- infant deaths: 유아 사망자 수 (1000명 당)
- Alcohol: 1인 당 알코올 섭취량 (순수 알코올, 리터 기준)
- percentage expenditure: GDP 중 건강 관련 지출액의 비중
- Hepatitis B: 1세 미만 영유아 중 헵티티스 B 백신 접종률
- Measles: 1000명 당 보고된 홍역 발병 건수
- BMI: 평균 BMI 지수
- under-five deaths: 1000명 당 5세 이하 사망자 수
- Polio: 1세 미만 영유아 중 폴리오(Pol3) 백신 접종률
- Total expenditure: 총 정부 지출 중 건강 지출 비중
- Diphtheria: 1세 미만의 영유아 중 디프테리아, 파상풍, 백일해(DTP) 예방접종률
- HIV/AIDS: 0~4세의 아이들 중 HIV/AIDS로 인한 1000명 당 사망자 수
- GDP: GDP
- Population: 국가 총 인구
- thinness 1-19 years: 10세에서 19세 사이의 아이들과 청소년들 사이에서 얇음 증후군의 유병률
- thinness 5-9 years: 5세에서 9세 사이의 아이들 사이에서 얇음 증후군의 유병률
- Income composition of resources: 소득 자원의 구성에 따른 인간 개발 지수(HDI)
- Schooling: 평균적인 교육 년수

#### Target

- Life expectancy: 기대수명

In [1]:
import pandas as pd

l_df = pd.read_csv('./datasets/life_expectancy.csv', low_memory=False)
l_df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [2]:
l_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [3]:
# 중복행 검사
l_df.duplicated().sum()

0

In [4]:
# 결측치 검사
l_df.isna().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [28]:
# 컬럼의 이름 양 옆에 공백이 있는 경우가 있으므로 처리
pre_l_df = l_df.copy()
for c in pre_l_df.columns:
    pre_l_df = pre_l_df.rename(columns={c: c.strip()})

In [29]:
pre_l_df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles', 'BMI', 'under-five deaths', 'Polio', 'Total expenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years',
       'thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')

- 타겟 데이터인 Life expectancy 의 결측치 부분은 행 전체를 삭제합니다.

In [30]:
pre_l_df = pre_l_df[~pre_l_df['Life expectancy'].isna()]
pre_l_df.isna().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
Hepatitis B                        553
Measles                              0
BMI                                 32
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
HIV/AIDS                             0
GDP                                443
Population                         644
thinness  1-19 years                32
thinness 5-9 years                  32
Income composition of resources    160
Schooling                          160
dtype: int64

In [32]:
pre_l_df[['Alcohol']].describe().T

          count      mean       std   min    25%   50%    75%    max
Alcohol  2735.0  4.614856  4.050749  0.01  0.905  3.77  7.715  17.87